### ISSUE TITLE
isCrowd flag for object detection?

### ISSUE THREAD

**Issue by yoyolin** [microsoft/vision-evaluation#14]
Do you plan to expand the capabilities to include isCrowd flag for object detection evaluation? It's widely used in SoTA benchmark repos like COCO, OpenImages etc.

**Comment by pj-ms** [comment]
Hi, 

Latest PR adds support for iscrowd flag, with onboarding cocoapi for mAP calculation. Details can be checked here: https://github.com/microsoft/vision-evaluation/blob/df386099cbc0f80224853762c7d5e580fee70e0a/vision_evaluation/evaluators.py#L553
